updates

diff --git a/php/.local/installs/composer b/php/.local/installs/composer
--- a/php/.local/installs/composer
+++ b/php/.local/installs/composer
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
 # [ -f scripts/composer ] && scripts/composer "${@}"; exit
 
@@ -6,9 +6,9 @@ php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
 ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
 
 if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then
-    >&2 echo 'ERROR: Invalid installer signature'
-    rm composer-setup.php
-    exit 1
+		>&2 echo 'ERROR: Invalid installer signature'
+		rm composer-setup.php
+		exit 1
 fi
 
 php composer-setup.php --quiet
