merges in mac

diff --git a/general/.local/bin/dev b/general/.local/bin/dev
--- a/general/.local/bin/dev
+++ b/general/.local/bin/dev
@@ -1,13 +1,23 @@
 #!/bin/bash
-#
-cd $CODE/$1
 
-if [ -e "$1.php" ]
-then
-    cd $CODE/$1 && vim -c "! phpunit" -O $1.php tests/$1Test.php
+if [[ "0" == "$#" ]] && [[ -d "${CODE}" ]]; then
+    cd "${CODE}" && tmux.sh
 fi
 
-if [ -e "$1.rb" ]
-then
-    cd $CODE/$1 && vim -c "! rspec $1_spec.rb" -O $1.rb $1_spec.rb
-fi
+case "$1" in
+    "api")
+	cd "${API}" && tmux.sh
+	;;
+    "config_management")
+	cd "${CONFIG_MANAGEMENT}" && tmux.sh
+	;;
+    "dotfiles")
+	cd "${DOTFILES}" && tmux.sh
+	;;
+    "web")
+	cd "${WEB}" && tmux.sh
+	;;
+    *)
+	echo "Project ${1} not found."
+	exit 1
+esac
